name: Packages

on:
  push:
    branches:
    - master
    paths:
    - 'json/**'
  pull_request:
    paths:
    - 'json/**'
  workflow_dispatch:
    inputs:
      packages:
        description: "A space-separated names of packages selected for rebuilding"
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v3.1.0
      - name: Install dependencies and scripts check
        run: |
          python -m pip install --upgrade pip
          python -m pip install ruamel.yaml termux-create-package
      - name: Build Package
        run: |
          set -x
          cd json/"$1"
          termux-create-package build.json
      - name: Upload Artifact
        uses: actions/upload-artifact@v3.0.0
        with:
          path: ./
      - name: Download Artifact
        uses: actions/download-artifact@v3.0.0
        with:
          path: ./
